#TODO: enable/disable exchanges here instead of adapters
##############################################
#                                            #
#                                            #
#                 API REGION                 #
#                                            #
#                                            #
##############################################
#Only tickers that will be saved in local cache
#api.includeTickers=AGLD,NEAR,SDL,SDN,BTC,ETH,ETC
#api.includeTickers=ETH
api.includeTickers=

kucoin.api.key.value=
kucoin.api.key.secret=

bybit.api.key.value=yLkjO77qPIj9aA8rcp
bybit.api.key.secret=0S3AVkeb02p2dmhxaS632wypYibl3RK1jzjJ

mexc.api.key.value=mx0vglO4RmjpQL54DF
mexc.api.key.secret=0673b58df5f848a9ba2c4282f92e21d8

binance.api.key.value=
binance.api.key.secret=

gate.api.key.value=
gate.api.key.secret=

huobi.api.key.value=
huobi.api.key.secret=

kucoin.adapter.enabled=true
mexc.adapter.enabled=false
bybit.adapter.enabled=false
binance.adapter.enabled=false
gate.adapter.enabled=false
huobi.adapter.enabled=false

#logging.level.reactor.netty.http.client=DEBUG
