##############################################
#                                            #
#                                            #
#             APPLICATION REGION             #
#                                            #
#                                            #
##############################################
app.healthcheck-interval-ms=5000
app.healthcheck-stale-threshold-ms=60000
##############################################
#                                            #
#                                            #
#                 API REGION                 #
#                                            #
#                                            #
##############################################
# Only tickers that will be saved in local cache
#coin.cache.included-tickers=AGLD,NEAR,SDL,SDN,BTC,ETH,ETC
# Empty - no tickers filter
coin.cache.included-tickers=

# Retrieving mode
# LIVE - emit event on each change      (low-latency)
# SCHEDULED - emit event at interval    (low-consistency)
coin.cache.mode=live
# Interval in SCHEDULED mode
coin.cache.scheduled-interval-ms=1000

##############################################
#                                            #
#                                            #
#              TRANSPORT REGION              #
#                                            #
#                                            #
##############################################
rest.retry-backoff-seconds=5
rest.price-calls-interval-ms=0
rest.availability-calls-interval-ms=30000

##############################################
#                                            #
#                                            #
#              INTEGRATION REGION            #
#                                            #
#                                            #
##############################################
integration.bybit-apikey-value=
integration.bybit-apikey-secret=

integration.mexc-apikey-value=
integration.mexc-apikey-secret=

##############################################
#                                            #
#                                            #
#               SPRING REGION                #
#                                            #
#                                            #
##############################################
spring.profiles.active=dev
#logging.level.reactor.netty=DEBUG
#logging.level.reactor.netty.http.client=DEBUG
#logging.level.org.springframework.web.reactive.function.client=DEBUG
#logging.level.io.netty.resolver.dns=TRACE
#logging.level.io.netty.resolver=DEBUG